### ISSUE TITLE
Please update meteor package to latest d3plus

### ISSUE THREAD

**Issue by bobiblazeski** [alexandersimoes/d3plus_meteor#1]
Please update meteor package to use latest d3plus 1.6.9, and if version is not and issues official version of the d3 package d3js:d3 https://atmospherejs.com/d3js/d3 which currently at version 3.4.13 as opposed to latest d3 3.5.2

**Comment by bobiblazeski** [comment]
Many  thanks. Just to inform you meteor for package for d3, d3js:d3 is updated.

**Comment by davelandry** [comment]
:beers: thanks for finding this, we're not too familiar with meteor but now we know how to keep it up to date.

**Comment by bobiblazeski** [comment]
Meteor folks are working on autopublishing  http://autopublish.meteor.com/ courtesy of @dandv & @splendido so soon expecting to see outdated packages in atmosphere as thing of a past.
